version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres-service
    environment:
      POSTGRES_DB: 'time_tracker_db'
      POSTGRES_USER: 'apuha'
      POSTGRES_PASSWORD: '12345678'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d time_tracker_db -U apuha" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - psql-data:/var/lib/postgresql/


networks:
  postgres:
    driver: bridge

volumes:
  psql-data: